'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IS_PRERELEASE() As Boolean
            Get
                Return CType(Me("IS_PRERELEASE"),Boolean)
            End Get
            Set
                Me("IS_PRERELEASE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DEVELOPER_MODE() As Boolean
            Get
                Return CType(Me("DEVELOPER_MODE"),Boolean)
            End Get
            Set
                Me("DEVELOPER_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EXECUTABLE_CURRENT_VERSION() As String
            Get
                Return CType(Me("EXECUTABLE_CURRENT_VERSION"),String)
            End Get
            Set
                Me("EXECUTABLE_CURRENT_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_PENDING() As Boolean
            Get
                Return CType(Me("UPDATE_PENDING"),Boolean)
            End Get
            Set
                Me("UPDATE_PENDING") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_PENDING_DOWNLOAD() As Boolean
            Get
                Return CType(Me("UPDATE_PENDING_DOWNLOAD"),Boolean)
            End Get
            Set
                Me("UPDATE_PENDING_DOWNLOAD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_PENDING_INSTALLATION() As Boolean
            Get
                Return CType(Me("UPDATE_PENDING_INSTALLATION"),Boolean)
            End Get
            Set
                Me("UPDATE_PENDING_INSTALLATION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_SILENT_INSTALL() As Boolean
            Get
                Return CType(Me("UPDATE_SILENT_INSTALL"),Boolean)
            End Get
            Set
                Me("UPDATE_SILENT_INSTALL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UPDATE_FOUND_CVERSION() As String
            Get
                Return CType(Me("UPDATE_FOUND_CVERSION"),String)
            End Get
            Set
                Me("UPDATE_FOUND_CVERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UPDATE_FOUND_CVERSION_WITHOUT_BUILDNBR() As String
            Get
                Return CType(Me("UPDATE_FOUND_CVERSION_WITHOUT_BUILDNBR"),String)
            End Get
            Set
                Me("UPDATE_FOUND_CVERSION_WITHOUT_BUILDNBR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UPDATE_FOUND_CHANGELOG() As String
            Get
                Return CType(Me("UPDATE_FOUND_CHANGELOG"),String)
            End Get
            Set
                Me("UPDATE_FOUND_CHANGELOG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UPDATE_FOUND_DOWNLOAD_LINK() As String
            Get
                Return CType(Me("UPDATE_FOUND_DOWNLOAD_LINK"),String)
            End Get
            Set
                Me("UPDATE_FOUND_DOWNLOAD_LINK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LAST_UPDATED_VERSION_CHECKED() As String
            Get
                Return CType(Me("LAST_UPDATED_VERSION_CHECKED"),String)
            End Get
            Set
                Me("LAST_UPDATED_VERSION_CHECKED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UPDATE_IGNORED_VERSION() As String
            Get
                Return CType(Me("UPDATE_IGNORED_VERSION"),String)
            End Get
            Set
                Me("UPDATE_IGNORED_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12/26/2018 06:00:57")>  _
        Public Property LAST_UPDATE_CHECK_DATE() As Date
            Get
                Return CType(Me("LAST_UPDATE_CHECK_DATE"),Date)
            End Get
            Set
                Me("LAST_UPDATE_CHECK_DATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DWM_EXTENSION() As Boolean
            Get
                Return CType(Me("DWM_EXTENSION"),Boolean)
            End Get
            Set
                Me("DWM_EXTENSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WIN_CLASSIC_ENHANCEMENTS() As Boolean
            Get
                Return CType(Me("WIN_CLASSIC_ENHANCEMENTS"),Boolean)
            End Get
            Set
                Me("WIN_CLASSIC_ENHANCEMENTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UI_DARK_MODE() As Boolean
            Get
                Return CType(Me("UI_DARK_MODE"),Boolean)
            End Get
            Set
                Me("UI_DARK_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LOCK_AT_TOPMOST() As Boolean
            Get
                Return CType(Me("LOCK_AT_TOPMOST"),Boolean)
            End Get
            Set
                Me("LOCK_AT_TOPMOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HIDE_TITLE() As Boolean
            Get
                Return CType(Me("HIDE_TITLE"),Boolean)
            End Get
            Set
                Me("HIDE_TITLE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HIDE_ICON() As Boolean
            Get
                Return CType(Me("HIDE_ICON"),Boolean)
            End Get
            Set
                Me("HIDE_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BLANK_ICON() As Boolean
            Get
                Return CType(Me("BLANK_ICON"),Boolean)
            End Get
            Set
                Me("BLANK_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ADDITIONAL_TITLE_TEXT() As Boolean
            Get
                Return CType(Me("ADDITIONAL_TITLE_TEXT"),Boolean)
            End Get
            Set
                Me("ADDITIONAL_TITLE_TEXT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ADDITIONAL_TITLE_TEXT_TYPE() As Integer
            Get
                Return CType(Me("ADDITIONAL_TITLE_TEXT_TYPE"),Integer)
            End Get
            Set
                Me("ADDITIONAL_TITLE_TEXT_TYPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Default Text")>  _
        Public Property CUSTOM_TITLE_TEXT() As String
            Get
                Return CType(Me("CUSTOM_TITLE_TEXT"),String)
            End Get
            Set
                Me("CUSTOM_TITLE_TEXT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property APP_OPACITY_TOGGLE() As Boolean
            Get
                Return CType(Me("APP_OPACITY_TOGGLE"),Boolean)
            End Get
            Set
                Me("APP_OPACITY_TOGGLE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property APP_OPACITY_APPLY_MODE() As Integer
            Get
                Return CType(Me("APP_OPACITY_APPLY_MODE"),Integer)
            End Get
            Set
                Me("APP_OPACITY_APPLY_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property APP_OPACITY() As Integer
            Get
                Return CType(Me("APP_OPACITY"),Integer)
            End Get
            Set
                Me("APP_OPACITY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SELECTED_THEME() As Integer
            Get
                Return CType(Me("SELECTED_THEME"),Integer)
            End Get
            Set
                Me("SELECTED_THEME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property WINVER_ICON() As Integer
            Get
                Return CType(Me("WINVER_ICON"),Integer)
            End Get
            Set
                Me("WINVER_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WINVER_USE_CURRENT_OS_ICON() As Boolean
            Get
                Return CType(Me("WINVER_USE_CURRENT_OS_ICON"),Boolean)
            End Get
            Set
                Me("WINVER_USE_CURRENT_OS_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property TASKMGR_ICON_LINE() As Integer
            Get
                Return CType(Me("TASKMGR_ICON_LINE"),Integer)
            End Get
            Set
                Me("TASKMGR_ICON_LINE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TASKMGR_ICON_BACK() As Integer
            Get
                Return CType(Me("TASKMGR_ICON_BACK"),Integer)
            End Get
            Set
                Me("TASKMGR_ICON_BACK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TASKMGR_USE_WINDOWS_ICON() As Boolean
            Get
                Return CType(Me("TASKMGR_USE_WINDOWS_ICON"),Boolean)
            End Get
            Set
                Me("TASKMGR_USE_WINDOWS_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_HELP_BTN() As Boolean
            Get
                Return CType(Me("SHOW_HELP_BTN"),Boolean)
            End Get
            Set
                Me("SHOW_HELP_BTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_SUGGESTUPDATE_BTN() As Boolean
            Get
                Return CType(Me("SHOW_SUGGESTUPDATE_BTN"),Boolean)
            End Get
            Set
                Me("SHOW_SUGGESTUPDATE_BTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_REPORTCRASH_BTN() As Boolean
            Get
                Return CType(Me("SHOW_REPORTCRASH_BTN"),Boolean)
            End Get
            Set
                Me("SHOW_REPORTCRASH_BTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_WINVER_BTN() As Boolean
            Get
                Return CType(Me("SHOW_WINVER_BTN"),Boolean)
            End Get
            Set
                Me("SHOW_WINVER_BTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BUILT_IN_WINVER() As Boolean
            Get
                Return CType(Me("BUILT_IN_WINVER"),Boolean)
            End Get
            Set
                Me("BUILT_IN_WINVER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SHOW_TASKMGR_BTN() As Boolean
            Get
                Return CType(Me("SHOW_TASKMGR_BTN"),Boolean)
            End Get
            Set
                Me("SHOW_TASKMGR_BTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property USE_SHELL32_ABOUTBOX() As Boolean
            Get
                Return CType(Me("USE_SHELL32_ABOUTBOX"),Boolean)
            End Get
            Set
                Me("USE_SHELL32_ABOUTBOX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HIDE_ALL_BOTTOM_BUTTONS() As Boolean
            Get
                Return CType(Me("HIDE_ALL_BOTTOM_BUTTONS"),Boolean)
            End Get
            Set
                Me("HIDE_ALL_BOTTOM_BUTTONS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SHOW_BTN_SEPARATORS() As Boolean
            Get
                Return CType(Me("SHOW_BTN_SEPARATORS"),Boolean)
            End Get
            Set
                Me("SHOW_BTN_SEPARATORS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAY_COMPLETEVERSION_IN_MAIN_WINDOW() As Boolean
            Get
                Return CType(Me("DISPLAY_COMPLETEVERSION_IN_MAIN_WINDOW"),Boolean)
            End Get
            Set
                Me("DISPLAY_COMPLETEVERSION_IN_MAIN_WINDOW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property MAINWINDOW_DISPLAYED_COLUMN_NBR() As Integer
            Get
                Return CType(Me("MAINWINDOW_DISPLAYED_COLUMN_NBR"),Integer)
            End Get
            Set
                Me("MAINWINDOW_DISPLAYED_COLUMN_NBR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_LUNARMAGIC() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_LUNARMAGIC"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_LUNARMAGIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_LUNAREXPAND() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_LUNAREXPAND"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_LUNAREXPAND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_RECOVERLM() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_RECOVERLM"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_RECOVERLM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_SNESGFX() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SNESGFX"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SNESGFX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_MARIOLPE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_MARIOLPE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_MARIOLPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_HEADDER() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_HEADDER"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_HEADDER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_HDMARIPPER() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_HDMARIPPER"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_HDMARIPPER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_MMLEDIT() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_MMLEDIT"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_MMLEDIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_ADDMUSICK() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_ADDMUSICK"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_ADDMUSICK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_LVMUSUTIL() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_LVMUSUTIL"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_LVMUSUTIL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_BRRPLAYER() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_BRRPLAYER"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_BRRPLAYER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_BLOCKREATOR() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_BLOCKREATOR"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_BLOCKREATOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_PIXI() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_PIXI"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_PIXI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_MODE7TILEMAP() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_MODE7TILEMAP"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_MODE7TILEMAP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SPC700PLAYER() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SPC700PLAYER"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SPC700PLAYER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_FLIPS() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_FLIPS"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_FLIPS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_STATUSEFFECTS() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_STATUSEFFECTS"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_STATUSEFFECTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_SNESCOLORTOOL() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SNESCOLORTOOL"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SNESCOLORTOOL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_EFFECTTOOLS() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_EFFECTTOOLS"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_EFFECTTOOLS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_GOPHERPOPCORNSTEW() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_GOPHERPOPCORNSTEW"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_GOPHERPOPCORNSTEW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_PETITEMM() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_PETITEMM"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_PETITEMM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_ASAR() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_ASAR"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_ASAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SNES_EMU() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SNES_EMU"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SNES_EMU") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_MARIOSTARTEDITOR() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_MARIOSTARTEDITOR"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_MARIOSTARTEDITOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_INTERACTIONEDIT() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_INTERACTIONEDIT"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_INTERACTIONEDIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_MULTIPLEMIDWAYPOINTS() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_MULTIPLEMIDWAYPOINTS"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_MULTIPLEMIDWAYPOINTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_SPRITEGFX() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SPRITEGFX"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SPRITEGFX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_GRAPHEDIT() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_GRAPHEDIT"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_GRAPHEDIT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_YYCHR() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_YYCHR"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_YYCHR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_SMWCUST() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWCUST"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWCUST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_SHTOOLS() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SHTOOLS"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SHTOOLS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_UBERASM() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_UBERASM"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_UBERASM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DISPLAYBTN_GRADIENTTOOL() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_GRADIENTTOOL"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_GRADIENTTOOL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SHOW_LEGACYABOUTBTN() As Boolean
            Get
                Return CType(Me("SHOW_LEGACYABOUTBTN"),Boolean)
            End Get
            Set
                Me("SHOW_LEGACYABOUTBTN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SHOW_APP_VERSION_STRING() As Boolean
            Get
                Return CType(Me("SHOW_APP_VERSION_STRING"),Boolean)
            End Get
            Set
                Me("SHOW_APP_VERSION_STRING") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SHOW_TRAY_ICON() As Boolean
            Get
                Return CType(Me("SHOW_TRAY_ICON"),Boolean)
            End Get
            Set
                Me("SHOW_TRAY_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_ABOUTDIALOG() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_ABOUTDIALOG"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_ABOUTDIALOG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_HELP() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_HELP"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_HELP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_SUGGESTUPDATE() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_SUGGESTUPDATE"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_SUGGESTUPDATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_SETTINGS() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_SETTINGS"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_SETTINGS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_RESTART() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_RESTART"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_RESTART") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property KEYBOARD_SCT_CUSTOMSHORTCUTS() As Boolean
            Get
                Return CType(Me("KEYBOARD_SCT_CUSTOMSHORTCUTS"),Boolean)
            End Get
            Set
                Me("KEYBOARD_SCT_CUSTOMSHORTCUTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUTS() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUTS"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_1() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_1"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_1_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_1_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_1_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_1_LAUNCH_WITH() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_1_LAUNCH_WITH"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_1_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_1_ICON() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_1_ICON"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_1_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_2() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_2"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_2_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_2_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_2_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_2_LAUNCH_WITH() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_2_LAUNCH_WITH"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_2_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_2_ICON() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_2_ICON"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_2_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_3() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_3"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_3_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_3_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_3_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_3_LAUNCH_WITH() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_3_LAUNCH_WITH"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_3_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_3_ICON() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_3_ICON"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_3_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_4() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_4"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_4_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_4_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_4_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_4_LAUNCH_WITH() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_4_LAUNCH_WITH"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_4_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_4_ICON() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_4_ICON"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_4_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_5() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_5"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_5_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_5_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_5_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_5_LAUNCH_WITH() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_5_LAUNCH_WITH"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_5_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_5_ICON() As Integer
            Get
                Return CType(Me("CUSTOM_SHORTCUT_5_ICON"),Integer)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_5_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ENABLE_CUSTOM_SHORTCUT_6() As Boolean
            Get
                Return CType(Me("ENABLE_CUSTOM_SHORTCUT_6"),Boolean)
            End Get
            Set
                Me("ENABLE_CUSTOM_SHORTCUT_6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CUSTOM_SHORTCUT_6_PATH() As String
            Get
                Return CType(Me("CUSTOM_SHORTCUT_6_PATH"),String)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_6_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_6_LAUNCH_WITH() As Decimal
            Get
                Return CType(Me("CUSTOM_SHORTCUT_6_LAUNCH_WITH"),Decimal)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_6_LAUNCH_WITH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CUSTOM_SHORTCUT_6_ICON() As Decimal
            Get
                Return CType(Me("CUSTOM_SHORTCUT_6_ICON"),Decimal)
            End Get
            Set
                Me("CUSTOM_SHORTCUT_6_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_SEARCH_AT_STARTUP() As Boolean
            Get
                Return CType(Me("UPDATE_SEARCH_AT_STARTUP"),Boolean)
            End Get
            Set
                Me("UPDATE_SEARCH_AT_STARTUP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_SEARCH_AT_STARTUP_DISCRETE_MODE() As Boolean
            Get
                Return CType(Me("UPDATE_SEARCH_AT_STARTUP_DISCRETE_MODE"),Boolean)
            End Get
            Set
                Me("UPDATE_SEARCH_AT_STARTUP_DISCRETE_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property USE_LEGACY_UPDATE_POPUPS() As Boolean
            Get
                Return CType(Me("USE_LEGACY_UPDATE_POPUPS"),Boolean)
            End Get
            Set
                Me("USE_LEGACY_UPDATE_POPUPS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ENABLE_UPDATE_INDICATOR_ON_ABOUT_WINDOW() As Boolean
            Get
                Return CType(Me("ENABLE_UPDATE_INDICATOR_ON_ABOUT_WINDOW"),Boolean)
            End Get
            Set
                Me("ENABLE_UPDATE_INDICATOR_ON_ABOUT_WINDOW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SHOW_UPDATE_SYSTEM_INFOS_ON_ABOUT_SCREEN() As Boolean
            Get
                Return CType(Me("SHOW_UPDATE_SYSTEM_INFOS_ON_ABOUT_SCREEN"),Boolean)
            End Get
            Set
                Me("SHOW_UPDATE_SYSTEM_INFOS_ON_ABOUT_SCREEN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_AUTOMATIC_DOWNLOAD() As Boolean
            Get
                Return CType(Me("UPDATE_AUTOMATIC_DOWNLOAD"),Boolean)
            End Get
            Set
                Me("UPDATE_AUTOMATIC_DOWNLOAD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_AUTOMATIC_INSTALLATION() As Boolean
            Get
                Return CType(Me("UPDATE_AUTOMATIC_INSTALLATION"),Boolean)
            End Get
            Set
                Me("UPDATE_AUTOMATIC_INSTALLATION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UPDATE_AUTOMATIC_INSTALLATION_SILENT_MODE() As Boolean
            Get
                Return CType(Me("UPDATE_AUTOMATIC_INSTALLATION_SILENT_MODE"),Boolean)
            End Get
            Set
                Me("UPDATE_AUTOMATIC_INSTALLATION_SILENT_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT1_ENABLED() As Boolean
            Get
                Return CType(Me("LM_SLOT1_ENABLED"),Boolean)
            End Get
            Set
                Me("LM_SLOT1_ENABLED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT1_ENABLE_HEADERMAGIC() As Boolean
            Get
                Return CType(Me("LM_SLOT1_ENABLE_HEADERMAGIC"),Boolean)
            End Get
            Set
                Me("LM_SLOT1_ENABLE_HEADERMAGIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lunar Magic Slot 1")>  _
        Public Property LM_SLOT1_NAME() As String
            Get
                Return CType(Me("LM_SLOT1_NAME"),String)
            End Get
            Set
                Me("LM_SLOT1_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LM_SLOT1_VERSION() As Integer
            Get
                Return CType(Me("LM_SLOT1_VERSION"),Integer)
            End Get
            Set
                Me("LM_SLOT1_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LM_SLOT1_PATH() As String
            Get
                Return CType(Me("LM_SLOT1_PATH"),String)
            End Get
            Set
                Me("LM_SLOT1_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT2_ENABLED() As Boolean
            Get
                Return CType(Me("LM_SLOT2_ENABLED"),Boolean)
            End Get
            Set
                Me("LM_SLOT2_ENABLED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT2_ENABLE_HEADERMAGIC() As Boolean
            Get
                Return CType(Me("LM_SLOT2_ENABLE_HEADERMAGIC"),Boolean)
            End Get
            Set
                Me("LM_SLOT2_ENABLE_HEADERMAGIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lunar Magic Slot 2")>  _
        Public Property LM_SLOT2_NAME() As String
            Get
                Return CType(Me("LM_SLOT2_NAME"),String)
            End Get
            Set
                Me("LM_SLOT2_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LM_SLOT2_VERSION() As Integer
            Get
                Return CType(Me("LM_SLOT2_VERSION"),Integer)
            End Get
            Set
                Me("LM_SLOT2_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LM_SLOT2_PATH() As String
            Get
                Return CType(Me("LM_SLOT2_PATH"),String)
            End Get
            Set
                Me("LM_SLOT2_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT3_ENABLED() As Boolean
            Get
                Return CType(Me("LM_SLOT3_ENABLED"),Boolean)
            End Get
            Set
                Me("LM_SLOT3_ENABLED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_SLOT3_ENABLE_HEADERMAGIC() As Boolean
            Get
                Return CType(Me("LM_SLOT3_ENABLE_HEADERMAGIC"),Boolean)
            End Get
            Set
                Me("LM_SLOT3_ENABLE_HEADERMAGIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lunar Magic Slot 3")>  _
        Public Property LM_SLOT3_NAME() As String
            Get
                Return CType(Me("LM_SLOT3_NAME"),String)
            End Get
            Set
                Me("LM_SLOT3_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LM_SLOT3_VERSION() As Integer
            Get
                Return CType(Me("LM_SLOT3_VERSION"),Integer)
            End Get
            Set
                Me("LM_SLOT3_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LM_SLOT3_PATH() As String
            Get
                Return CType(Me("LM_SLOT3_PATH"),String)
            End Get
            Set
                Me("LM_SLOT3_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_1CTL_ENABLED() As Boolean
            Get
                Return CType(Me("LM_1CTL_ENABLED"),Boolean)
            End Get
            Set
                Me("LM_1CTL_ENABLED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LM_1CTL_SHOW_SELECTOR_ON_CTRLCLICK() As Boolean
            Get
                Return CType(Me("LM_1CTL_SHOW_SELECTOR_ON_CTRLCLICK"),Boolean)
            End Get
            Set
                Me("LM_1CTL_SHOW_SELECTOR_ON_CTRLCLICK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LM_1CTL_SELECTED_VERSION() As Integer
            Get
                Return CType(Me("LM_1CTL_SELECTED_VERSION"),Integer)
            End Get
            Set
                Me("LM_1CTL_SELECTED_VERSION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SNES_SELECTED_EMULATOR() As Integer
            Get
                Return CType(Me("SNES_SELECTED_EMULATOR"),Integer)
            End Get
            Set
                Me("SNES_SELECTED_EMULATOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SNES9x_PATH_x86() As String
            Get
                Return CType(Me("SNES9x_PATH_x86"),String)
            End Get
            Set
                Me("SNES9x_PATH_x86") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SNES9x_PATH_x64() As String
            Get
                Return CType(Me("SNES9x_PATH_x64"),String)
            End Get
            Set
                Me("SNES9x_PATH_x64") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SNES9x_SELECTED_ARCH() As Integer
            Get
                Return CType(Me("SNES9x_SELECTED_ARCH"),Integer)
            End Get
            Set
                Me("SNES9x_SELECTED_ARCH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SNES9x_USE_COLORED_ICON() As Boolean
            Get
                Return CType(Me("SNES9x_USE_COLORED_ICON"),Boolean)
            End Get
            Set
                Me("SNES9x_USE_COLORED_ICON") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BSNES_PATH_x64() As String
            Get
                Return CType(Me("BSNES_PATH_x64"),String)
            End Get
            Set
                Me("BSNES_PATH_x64") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_ILBPE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_ILBPE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_ILBPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWBBPE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWBBPE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWBBPE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWENI() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWENI"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWENI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWENE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWENE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWENE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWMTE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWMTE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWMTE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWPTE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWPTE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWPTE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWSBE() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWSBE"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWSBE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DISPLAYBTN_SMWTYMI() As Boolean
            Get
                Return CType(Me("DISPLAYBTN_SMWTYMI"),Boolean)
            End Get
            Set
                Me("DISPLAYBTN_SMWTYMI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_ILBPE_PATH() As String
            Get
                Return CType(Me("SH_ILBPE_PATH"),String)
            End Get
            Set
                Me("SH_ILBPE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWBBPE_PATH() As String
            Get
                Return CType(Me("SH_SMWBBPE_PATH"),String)
            End Get
            Set
                Me("SH_SMWBBPE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWENI_PATH() As String
            Get
                Return CType(Me("SH_SMWENI_PATH"),String)
            End Get
            Set
                Me("SH_SMWENI_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWENE_PATH() As String
            Get
                Return CType(Me("SH_SMWENE_PATH"),String)
            End Get
            Set
                Me("SH_SMWENE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWMTE_PATH() As String
            Get
                Return CType(Me("SH_SMWMTE_PATH"),String)
            End Get
            Set
                Me("SH_SMWMTE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWPTE_PATH() As String
            Get
                Return CType(Me("SH_SMWPTE_PATH"),String)
            End Get
            Set
                Me("SH_SMWPTE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWSBE_PATH() As String
            Get
                Return CType(Me("SH_SMWSBE_PATH"),String)
            End Get
            Set
                Me("SH_SMWSBE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SH_SMWTYMI_PATH() As String
            Get
                Return CType(Me("SH_SMWTYMI_PATH"),String)
            End Get
            Set
                Me("SH_SMWTYMI_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LUNAREXPAND_PATH() As String
            Get
                Return CType(Me("LUNAREXPAND_PATH"),String)
            End Get
            Set
                Me("LUNAREXPAND_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RECOVERLM_PATH() As String
            Get
                Return CType(Me("RECOVERLM_PATH"),String)
            End Get
            Set
                Me("RECOVERLM_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SNESGFX_PATH() As String
            Get
                Return CType(Me("SNESGFX_PATH"),String)
            End Get
            Set
                Me("SNESGFX_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MARIOLLPE_PATH() As String
            Get
                Return CType(Me("MARIOLLPE_PATH"),String)
            End Get
            Set
                Me("MARIOLLPE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HEADDER_PATH() As String
            Get
                Return CType(Me("HEADDER_PATH"),String)
            End Get
            Set
                Me("HEADDER_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property HDMA_GRAD_RIPPER_PATH() As String
            Get
                Return CType(Me("HDMA_GRAD_RIPPER_PATH"),String)
            End Get
            Set
                Me("HDMA_GRAD_RIPPER_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MMLEDIT_PATH() As String
            Get
                Return CType(Me("MMLEDIT_PATH"),String)
            End Get
            Set
                Me("MMLEDIT_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ADDMUSICK_CMD_PATH() As String
            Get
                Return CType(Me("ADDMUSICK_CMD_PATH"),String)
            End Get
            Set
                Me("ADDMUSICK_CMD_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ADDMUSICK_GUI_PATH() As String
            Get
                Return CType(Me("ADDMUSICK_GUI_PATH"),String)
            End Get
            Set
                Me("ADDMUSICK_GUI_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LVMUSUTIL_PATH() As String
            Get
                Return CType(Me("LVMUSUTIL_PATH"),String)
            End Get
            Set
                Me("LVMUSUTIL_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BRRPLAYER_PATH() As String
            Get
                Return CType(Me("BRRPLAYER_PATH"),String)
            End Get
            Set
                Me("BRRPLAYER_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BLOCKREATOR_PATH() As String
            Get
                Return CType(Me("BLOCKREATOR_PATH"),String)
            End Get
            Set
                Me("BLOCKREATOR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PIXI_MAIN_PATH() As String
            Get
                Return CType(Me("PIXI_MAIN_PATH"),String)
            End Get
            Set
                Me("PIXI_MAIN_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PIXI_CONFIG_PATH() As String
            Get
                Return CType(Me("PIXI_CONFIG_PATH"),String)
            End Get
            Set
                Me("PIXI_CONFIG_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property M7MAP_PATH() As String
            Get
                Return CType(Me("M7MAP_PATH"),String)
            End Get
            Set
                Me("M7MAP_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SPC700PLAYER_PATH() As String
            Get
                Return CType(Me("SPC700PLAYER_PATH"),String)
            End Get
            Set
                Me("SPC700PLAYER_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FLOATINGIPS_PATH() As String
            Get
                Return CType(Me("FLOATINGIPS_PATH"),String)
            End Get
            Set
                Me("FLOATINGIPS_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property STATUSEFFECTS_PATH() As String
            Get
                Return CType(Me("STATUSEFFECTS_PATH"),String)
            End Get
            Set
                Me("STATUSEFFECTS_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SNESCOLORTOOL_PATH() As String
            Get
                Return CType(Me("SNESCOLORTOOL_PATH"),String)
            End Get
            Set
                Me("SNESCOLORTOOL_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EFFECTTOOL_PATH() As String
            Get
                Return CType(Me("EFFECTTOOL_PATH"),String)
            End Get
            Set
                Me("EFFECTTOOL_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GOPHERPOPCORNSTEW_PATH() As String
            Get
                Return CType(Me("GOPHERPOPCORNSTEW_PATH"),String)
            End Get
            Set
                Me("GOPHERPOPCORNSTEW_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PETITEMM_PATH() As String
            Get
                Return CType(Me("PETITEMM_PATH"),String)
            End Get
            Set
                Me("PETITEMM_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ASAR_PATH() As String
            Get
                Return CType(Me("ASAR_PATH"),String)
            End Get
            Set
                Me("ASAR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MARIOSTARTEDITOR_PATH() As String
            Get
                Return CType(Me("MARIOSTARTEDITOR_PATH"),String)
            End Get
            Set
                Me("MARIOSTARTEDITOR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property INTERACTIONEDITOR_PATH() As String
            Get
                Return CType(Me("INTERACTIONEDITOR_PATH"),String)
            End Get
            Set
                Me("INTERACTIONEDITOR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MULTIPLEMIDWAYPOINTS_PATH() As String
            Get
                Return CType(Me("MULTIPLEMIDWAYPOINTS_PATH"),String)
            End Get
            Set
                Me("MULTIPLEMIDWAYPOINTS_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SPRITEGFXCREATOR_PATH() As String
            Get
                Return CType(Me("SPRITEGFXCREATOR_PATH"),String)
            End Get
            Set
                Me("SPRITEGFXCREATOR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GRAPHICEDITOR_PATH() As String
            Get
                Return CType(Me("GRAPHICEDITOR_PATH"),String)
            End Get
            Set
                Me("GRAPHICEDITOR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property YYCHR_PATH() As String
            Get
                Return CType(Me("YYCHR_PATH"),String)
            End Get
            Set
                Me("YYCHR_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SMWCUSTOMIZER_PATH() As String
            Get
                Return CType(Me("SMWCUSTOMIZER_PATH"),String)
            End Get
            Set
                Me("SMWCUSTOMIZER_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UBERASM_PATH() As String
            Get
                Return CType(Me("UBERASM_PATH"),String)
            End Get
            Set
                Me("UBERASM_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GRADIENTTOOL_PATH() As String
            Get
                Return CType(Me("GRADIENTTOOL_PATH"),String)
            End Get
            Set
                Me("GRADIENTTOOL_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EX_SET_DARKMODE_HOMEUPDATEBAR() As Boolean
            Get
                Return CType(Me("EX_SET_DARKMODE_HOMEUPDATEBAR"),Boolean)
            End Get
            Set
                Me("EX_SET_DARKMODE_HOMEUPDATEBAR") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SMW_MultiTool_Launcher.My.MySettings
            Get
                Return Global.SMW_MultiTool_Launcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
