'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMW_MultiTool_Launcher.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à MMMM dd, yyyy.
        '''</summary>
        Friend Shared ReadOnly Property App_Const_CompDate_Frm() As String
            Get
                Return ResourceManager.GetString("App_Const_CompDate_Frm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à en-US.
        '''</summary>
        Friend Shared ReadOnly Property App_Const_CompDate_Lng() As String
            Get
                Return ResourceManager.GetString("App_Const_CompDate_Lng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Apply.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Apply() As String
            Get
                Return ResourceManager.GetString("App_GText_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Browse.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Browse() As String
            Get
                Return ResourceManager.GetString("App_GText_Browse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Cancel() As String
            Get
                Return ResourceManager.GetString("App_GText_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choose.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Choose() As String
            Get
                Return ResourceManager.GetString("App_GText_Choose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Close.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Close() As String
            Get
                Return ResourceManager.GetString("App_GText_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Error.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Error() As String
            Get
                Return ResourceManager.GetString("App_GText_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Critical Error.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_ErrorC() As String
            Get
                Return ResourceManager.GetString("App_GText_ErrorC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fatal Error.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_ErrorF() As String
            Get
                Return ResourceManager.GetString("App_GText_ErrorF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_No() As String
            Get
                Return ResourceManager.GetString("App_GText_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_OK() As String
            Get
                Return ResourceManager.GetString("App_GText_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Open.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Open() As String
            Get
                Return ResourceManager.GetString("App_GText_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Yes.
        '''</summary>
        Friend Shared ReadOnly Property App_GText_Yes() As String
            Get
                Return ResourceManager.GetString("App_GText_Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Config file is missing.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_ConfigFile_Missing_InstructionText() As String
            Get
                Return ResourceManager.GetString("Msg_TD_ConfigFile_Missing_InstructionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The file &quot;{0}&quot; is missing in the program folder.
        '''Please check if the file is present, or go to the website to get a copy of the file..
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_ConfigFile_Missing_Text() As String
            Get
                Return ResourceManager.GetString("Msg_TD_ConfigFile_Missing_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Copy exception information into clipboard.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_GeneralException_BtnCopy() As String
            Get
                Return ResourceManager.GetString("Msg_TD_GeneralException_BtnCopy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Error details:
        '''
        '''{0}.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_GeneralException_ExpandedText() As String
            Get
                Return ResourceManager.GetString("Msg_TD_GeneralException_ExpandedText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à View error details.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_GeneralException_SeeDetailsText() As String
            Get
                Return ResourceManager.GetString("Msg_TD_GeneralException_SeeDetailsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à An unhandled exception occured, which caused the current action requested to end. The error reported is:
        '''
        '''{0}.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_GeneralException_Text() As String
            Get
                Return ResourceManager.GetString("Msg_TD_GeneralException_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Unhandled exception.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_GeneralException_Title() As String
            Get
                Return ResourceManager.GetString("Msg_TD_GeneralException_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à See older LTS Versions.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_UnsupportedOS_BtnSeeLTS() As String
            Get
                Return ResourceManager.GetString("Msg_TD_UnsupportedOS_BtnSeeLTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supported Operating Systems.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_UnsupportedOS_BtnSupportedOS() As String
            Get
                Return ResourceManager.GetString("Msg_TD_UnsupportedOS_BtnSupportedOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Operating System is not supported.
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_UnsupportedOS_InstructionText() As String
            Get
                Return ResourceManager.GetString("Msg_TD_UnsupportedOS_InstructionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Current Operating System is not supported by this {0} version.
        '''
        '''If you still want to use {0} with your current OS, check for 2.10-LTS versions..
        '''</summary>
        Friend Shared ReadOnly Property Msg_TD_UnsupportedOS_Text() As String
            Get
                Return ResourceManager.GetString("Msg_TD_UnsupportedOS_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Compiled on.
        '''</summary>
        Friend Shared ReadOnly Property UI_Frm02_CompStr_Compiled() As String
            Get
                Return ResourceManager.GetString("UI_Frm02_CompStr_Compiled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à About.
        '''</summary>
        Friend Shared ReadOnly Property UI_Frm02_FrmTitle() As String
            Get
                Return ResourceManager.GetString("UI_Frm02_FrmTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Build.
        '''</summary>
        Friend Shared ReadOnly Property UI_Frm02_VersionStr_Build() As String
            Get
                Return ResourceManager.GetString("UI_Frm02_VersionStr_Build", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version.
        '''</summary>
        Friend Shared ReadOnly Property UI_Frm02_VersionStr_Version() As String
            Get
                Return ResourceManager.GetString("UI_Frm02_VersionStr_Version", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
